version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: huubr-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: huubr_user
      POSTGRES_PASSWORD: huubr_password
      POSTGRES_DB: huubr_db
    volumes:
      - huubr_postgres_data:/var/lib/postgresql/data

volumes:
  huubr_postgres_data: